name: githubworkflow
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  my_first_job:
    name: My first job
    runs-on: self-hosted
    steps:
      - name: Print a greeting
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
  
