name: githubworkflow
on:
  push:
    branches:
      - main
      - 'feature/**'
permissions:
  id-token: write
  contents: read  
jobs:
  terrFORMJOB:
    name: terraformjob
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: 6bf3e812-0c5b-4155-92c0-33d9a154ef16
          tenant-id: e92dda8b-a61d-4340-beaf-a377190b69f4
          subscription-id: ef88ee82-ddb3-44a3-970a-7a8e3296f3f5
      
  
